### ISSUE TITLE
Long-term monitoring of coral reef fish assemblages in the Western central pacific

### ISSUE THREAD

**Issue by gbif-portal** [gbif/data-mobilization#101]
## Long-term monitoring of coral reef fish assemblages in the Western central pacific

Dataset link: https://doi.org/10.6084/m9.figshare.c.3808039

Region: Pacific Islands

Taxon: Marine reef

Type: sampling event

Why is this important: **SEE #70 ** A dataset from a large-scale monitoring program that surveys coral reef fish assemblages and habitats in the US-affiliated tropical Pacific. Currently, this includes &gt;4000 surveys from 39 islands and atolls in Hawaii (including the main and Northwestern Hawaiian Islands) and affiliated geo-political regions of American Samoa, the Commonwealth of the Northern Mariana Islands, Guam, and the Pacific Remote Islands Areas. The dataset spans 2010-2017 and uses the stationary point count method to survey the fish assemblage and a rapid visual assessment of the benthos.

License: CC0 1.0

Bibliographic reference: https//doi.org/10.1038/sdata.2017.176

Dataholders contact information: [Adel Heenan](adel.heenan@noaa.gov)

Users contact info: @kcopas

**Comment by albenson-usgs** [comment]
https://www.gbif.org/dataset/f56fb306-32e4-4b96-a381-6b87c186ad0f
