### ISSUE TITLE
NEON sampling-event datasets

### ISSUE THREAD

**Issue by kcopas** [gbif/data-mobilization#116]
Dataset link: http://data.neonscience.org/browse-data?showAllDates=true&showAllSites=true&showTheme=org

Region: Sentinel sites in US

Taxon: Various

Type: sampling-event

Priority: high

License: Not an open license 

Bibliographical reference: http://onlinelibrary.wiley.com/doi/10.1002/ecs2.1744/full

Comments: Major NSF-funded LTER observatory network. Source of ongoing site-based inventory.

@dschigel has had previous discussions with Kate Thibault and Sara Elmendorg about collaboration. Eric Sokol was identified as most active on matters of data interoperability.

Looks as if there are several relevant datasets already, though temporal and geographic coverage is not yet complete for the NEON network:
*Terrestrial*
+ Ground beetles sampled from pitfall traps
+ Mosquitoes sampled from CO2 traps
+ Plant phenology observations
+ Plant presence and percent cover
+ Small mammal box trapping
+ Ticks sampled using drag cloths

*Freshwater*
+ Aquatic plant, bryophyte, lichen, and macroalgae point counts in wadeable streams
+ Fish electrofishing, gill netting, and fyke netting counts
+ Macroinvertebrate collection
+ Periphyton, seston, and phytoplankton collection
+ Zooplankton collection

NB: In Helsinki, I briefly raised the issue of licensing status of NEON data with the U.S. HOD, who manages the project for NSF. He suggested that in fact the data should be open, but we definitely need discussion and clarification based the [current proprietorial language](http://data.neonscience.org/data-policy).

Dataholders contact information: [Eric Sokol](esokol@battelleecology.org), [Kate Thibault](kthibault@battelleecology.org), [Sarah Elmendorf](selmendorf@battelleecology.org)

Users contact info: @kcopas

**Comment by dnoesgaard** [comment]
![image](https://user-images.githubusercontent.com/21358085/42466643-c263fbc0-83af-11e8-98a6-b713df1c1fa4.png)

**Comment by kcopas** [comment]
Current positive discussions about data sharing likely derailed with major changes in NEON staff
> [NEON ecological observatory in crisis again: Top scientist quits, Battelle fires advisory board and senior managers](http://www.sciencemag.org/news/2019/01/neon-ecological-observatory-crisis-again-top-scientist-quits-battelle-fires-advisory)

**Comment by sformel-usgs** [comment]
This discussion was pointed out to me. Curious if a conclusion was ever reached? It looks like there are 45 NEON datasets in GBIF already, and we're planning on mobilizing some more.

**Comment by kcopas** [comment]
Thanks for digging through the bins, Steve! Yes, our collaboration with [NEON](https://www.gbif.org/publisher/e794e60e-e558-4549-99f8-cfb241cdce24/metrics) is very much on track. Closing…
