### ISSUE TITLE
xeno-canto

### ISSUE THREAD

**Issue by gbif-portal** [gbif/data-mobilization#12]
## xeno-canto

Dataset link: http://www.xeno-canto.org/explore?dir=0&amp;order=xc

Region: Global

Taxon: Birds

Type: occurrence

Why is this important: Observations are supported by audio recordings of birdsong

Priority: low

Comments: Tim Hirsch and I have corresponded every year or so with this group, which receives substantial support from Naturalis, either directly or through the Dutch node. With the changes at NLBIF, it&#39;s probably good to put this on Henk and Isabel&#39;s radar, as the contacts seem generally supportive of the idea. 

Note that one potential stumbling block is the licensing (http://www.xeno-canto.org/about/terms), which allows contributors to assign BY-SA, BY-NC-ND and BY-NC-SA.

Dataholders contact information: Willem-Pier Vellinga (wp@xeno-canto.org); Bob Planqué (bob@xeno-canto.org)

Users contact info: kcopas@gbif.org

**Comment by MattBlissett** [comment]
Looks like it's now with us: https://www.gbif.org/dataset/b1047888-ae52-4179-9dd5-5448ea342a24

**Comment by timrobertson100** [comment]
With audio too (although see https://github.com/gbif/portal-feedback/issues/1630)

**Comment by timhirsch** [comment]
Fabulous that these records are now in!
