### ISSUE TITLE
Occurrence-only data

### ISSUE THREAD

**Issue by gbif-portal** [gbif/data-mobilization#131]
## Occurrence-only data

Dataset link: https://www.inaturalist.org/observations/10069490

Region: India

Taxon: Halyomorpha scutellata

Type: occurrence

Why is this important: Very rare species.

Priority: high

License: CC-BY-NC 4.0

Dataholders contact information: jemuelstanley47@gmail.com

Users contact info: jemuelstanley47@gmail.com

**Comment by ahahn-gbif** [comment]
All iNaturalist research-grade data are already connected to GBIF.org. See e.g. https://www.gbif.org/occurrence/search?q=Halyomorpha%20scutellata&dataset_key=50c9509d-22c7-4a22-a47d-8c48425ef4a7.
