### ISSUE TITLE
Invasive species occurrences from Nepal via ICIMOD

### ISSUE THREAD

**Issue by kcopas** [gbif/data-mobilization#140]
A citation of the ISSG checklist for Nepal via GBIF led me back to [Potential impact of climate change on the distribution of six invasive alien plants in Nepal](https://doi.org/10.1016/j.ecolind.2018.07.009), which cites as several ICIMOD reports as the source of well over 5,000 species occurrence records (see also Table 1): 

> The occurrence data of these IAPs (Fig. 1) were obtained from field surveys conducted in various localities of Nepal from 2013 to 2017 (Shrestha, 2014, Siwakoti et al., 2016, Shrestha et al., 2016, Shrestha et al., 2018b). 

What's keeping this from entering the realm of open data? ICIMOD has 14 checklists and no occurrences.

ping @timhirsch

**Comment by timhirsch** [comment]
Yes I plan to raise this in Kathmandu

**Comment by timhirsch** [comment]
Incidentally the citation of the Nepal ISSG checklist is somewhat circular as the lead author of the paper is also the lead of the GRIIS country team (welcome nevertheless). The same person is running a BIFA data mobilization project and will be attending the upcoming Asia nodes meeting, and I hope this will be the first step to unlock what is undoubtedly a significant volume of ICIMOD data so far not published through GBIF.

**Comment by lilee-sh** [comment]
Author of Invasive Alien Plants occurrences from ICIMOD contacted.

**Comment by lilee-sh** [comment]
Working on the first set of dataset from Kailash Sacred Landscape

**Comment by lilee-sh** [comment]
First dataset published with 587 occurrences: https://www.gbif.org/dataset/d02c46ba-f33c-47c7-be1d-e4083373182f
