### ISSUE TITLE
FLOTROP

### ISSUE THREAD

**Issue by gbif-portal** [gbif/data-mobilization#142]
## FLOTROP

Dataset link: https://filesender.renater.fr/?s=download&amp;token=6605bd21-e3fa-db01-593c-992269b6f182

Region: africa ( Northern Tropical Africa)

Taxon: plantae

Type: occurrence

Why is this important: The FLOTROP dataset contains numerous plant observations (around 340,000 occurrences) in northern tropical Africa (from the 5th to 25th parallel north) in open ecosystems (savannah and steppe). They were collected by multiple collectors between 1920 and 2012 and were managed by Philippe Daget. These observations are probably the most important and unique source of plant distribution over the Sahel area. The data are now available in the Global Biodiversity Information Facility (GBIF), Tela Botanica website, and as maps in the African Plant Database. For the overall area involved, this dataset has increased by 40% the data available in the GIBF. For some countries between the 15th and 21st parallel north, the FLOTROP dataset has increased available occurrences 10-fold compared to the data existing in the GIBF.

Priority: medium

License: CC-BY-NC 4.0

Bibliographic reference: Data paper in Preparation,La base FLOTROP et L&#39;inventaire de la flore des pâturages d&#39;Afrique sahélienne A. Gaston and Ph. Daget Systematics and Geography of Plants Vol. 71, No. 2, Plant Systematics and Phytogeography for the Understanding of African Biodiversity (2001), pp. 337-344

Comments: A data paper is in preparation and will be submit when the data are available on the GIBF.

Dataholders contact information: Simon Taugourdeau ( CIRAD SELMET)

Users contact info: simon.taugourdeau@cirad.fr

**Comment by ahahn-gbif** [comment]
Dataset available at https://www.gbif.org/dataset/eb605c7a-a91c-4ab8-a588-85d0ccb2be9e
Also see: https://www.nature.com/articles/s41597-019-0120-8
Closing.
