### ISSUE TITLE
Pl@ntNet

### ISSUE THREAD

**Issue by gbif-portal** [gbif/data-mobilization#148]
## Pl@ntNet

Dataset link: https://plantnet.org/en/

Region: Europe, Africa, Eastern-Mediterranean, America, Pacific

Taxon: Plantae

Type: occurrence

Why is this important: Pl@ntNet documents plant diversity around the world. One if its projects documented 3030 species in North Africa and an other one 1118 in Eastern Mediterranean, two regions for which GBIF has little data.

Priority: low

License: Unspecified

Users contact info: ManonGros

**Comment by kcopas** [comment]
Hi @pamerlon—I'm sure I've asked about Anne-Sophie about this dataset before, but my feeble brain won't recall the facts. Just saw an [interesting piece](https://qz.com/1615237/plntnet-is-the-worlds-best-social-network/) about it from an American fan, so I thought I'd push past the shame and ask again.

At one point I thought some of this was coming in via Tele-Botanica, but I'm not so sure about that now—can't see any indication that the data is open, malheuresment...

**Comment by ManonGros** [comment]
Now in GBIF: https://www.gbif.org/publisher/da86174a-a605-43a4-a5e8-53d484152cd3
