### ISSUE TITLE
PSG recordings

### ISSUE THREAD

**Issue by gbif-portal** [gbif/data-mobilization#173]
## PSG recordings

Region: ASIA

Taxon: EOG

Type: undefined

Why is this important: we used PSG data from 16 healthy individuals(sleep efficiency (SE)≥85%) and 16 insomnia patients (sleepefficiency (SE)&lt;85%) recruited from the public by onlineadvertisements

Priority: high

**Comment by ahahn-gbif** [comment]
Not enough detail to pursue and out of scope - closing.
