### ISSUE TITLE
Clinical Psychologist

### ISSUE THREAD

**Issue by gbif-portal** [gbif/data-mobilization#196]
## Clinical Psychologist

Dataset link: https://etymonpsychology.com/

Region: Dublin, Ireland

Taxon: Mental Health

Type: occurrence

Why is this important: Our services of Psychology Dublin and Psychotherapy in Dublin for all the spectrum of problems or disorders of human suffering.

Priority: low

License: Unspecified

Dataholders contact information: info@etymonpsychology.com

Users contact info: +353 89 232 4477

**Comment by dschigel** [comment]
spam
