### ISSUE TITLE
Hungarian Natural History Museum

### ISSUE THREAD

**Issue by gbif-portal** [gbif/data-mobilization#198]
## Hungarian Natural History Museum

Dataset link: http://data.ggbn.org/ggbn_portal/search/result?institution=HNHM%2C+Budapest

Region: Hungary, Pannonian Biogeographical Region

Taxon: Biota

Type: occurrence

Why is this important: Some discussion by DS in Budapest and moderate interest towards GBIF. Established and working link with GGBN

Priority: high

License: Unspecified

Comments: Last contact 2017

Dataholders contact information: Gabor CSORBA PhD csorba@nhmus.hu Hungarian Natural History Museum H-1088 Budapest, Baross u. 13.

Users contact info: dschigel

**Comment by jlegind** [comment]
registered in GBIF in 2010
