### ISSUE TITLE
jacleonardi observations iNaturalist research grade

### ISSUE THREAD

**Issue by gbif-portal** [gbif/data-mobilization#199]
## jacleonardi observations iNaturalist research grade

Dataset link: https://www.inaturalist.org/observations?place_id=any&amp;quality_grade=research&amp;subview=grid&amp;user_id=jacleonardi&amp;verifiable=any

Region: world

Taxon: birds, plants, mammals, insects, molluscs, mushrooms

Why is this important: &gt;500 research grade observation of 323 species, with an on-going uploading of my photo collection. I&#39;m a researcher, privately interested in biodiversity protection.

Priority: low

License: CC-BY-NC 4.0

**Comment by kcopas** [comment]
[cough] https://www.gbif.org/occurrence/search?dataset_key=50c9509d-22c7-4a22-a47d-8c48425ef4a7&recorded_by=Jacques%20Leonardi&advanced=1

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ahahn-gbif** [comment]
All iNaturalist research-grade data are already connected to GBIF.org.
