### ISSUE TITLE
Neurothemis fulvia

### ISSUE THREAD

**Issue by gbif-portal** [gbif/data-mobilization#202]
## Neurothemis fulvia

Dataset link: https://www.inaturalist.org/observations/66949255

Region: Sumatra

Taxon: Neurothemis fulvia

Type: occurrence

Priority: low

License: Unspecified

Dataholders contact information: kevin123lita@gmail.com

Users contact info: kevin123lita@gmail.com

**Comment by ahahn-gbif** [comment]
All iNaturalist research-grade data are already connected to GBIF.org.
