### ISSUE TITLE
Neurothemis feralis

### ISSUE THREAD

**Issue by gbif-portal** [gbif/data-mobilization#203]
## Neurothemis feralis

Dataset link: https://www.inaturalist.org/observations/67297647

Region: Java

Taxon: Neurothemis feralis

Type: occurrence

Why is this important: Maybe the first living photo posted to iNat

Priority: medium

Users contact info: kevin123lita@gmail.com

**Comment by ahahn-gbif** [comment]
All iNaturalist research-grade data are already connected to GBIF.org.
