### ISSUE TITLE
Xylocopa

### ISSUE THREAD

**Issue by gbif-portal** [gbif/data-mobilization#204]
## Xylocopa

Dataset link: https://www.inaturalist.org/observations/66864735

Region: Sumatra

Taxon: Xylocopa auripennis iridipennis

Type: occurrence

Priority: high

License: Unspecified

Dataholders contact information: kevin123lita@gmail.com

Users contact info: kevin123lita@gmail.com

**Comment by ahahn-gbif** [comment]
All iNaturalist research-grade data are already connected to GBIF.org.
