### ISSUE TITLE
Cyclosia panthona

### ISSUE THREAD

**Issue by gbif-portal** [gbif/data-mobilization#205]
## Cyclosia panthona

Dataset link: https://www.inaturalist.org/observations/68443007

Region: Sumatra

Taxon: Cyclosia panthoba

Type: occurrence

Priority: low

License: Unspecified

Dataholders contact information: Kevin123lita@gmail.com

Users contact info: Kevin123lita@gmail.com

**Comment by ahahn-gbif** [comment]
All iNaturalist research-grade data are already connected to GBIF.org.
