### ISSUE TITLE
NHMD Invertebrate Zoology Collection

### ISSUE THREAD

**Issue by gbif-portal** [gbif/data-mobilization#209]
## NHMD Invertebrate Zoology Collection

Dataset link: https://specify-snm.science.ku.dk/static/depository/export_feed/DwCA-IV-full.zip

Region: World

Taxon: Invertebrates

Type: occurrence

Why is this important: Many Bothans died to bring us this information.

Priority: high

Comments: This is a test.

Dataholders contact information: tschioette@snm.ku.dk

Users contact info: fedor.steeman@snm.ku.dk

**Comment by ahahn-gbif** [comment]
Suspected misunderstanding of the suggesting tool as a data upload option. In active collaboration with @thomasstjerne - closing
