### ISSUE TITLE
Anopheles of Copenhagen

### ISSUE THREAD

**Issue by gbif-portal** [gbif/data-mobilization#217]
## Anopheles of Copenhagen

Dataset link: www.google.com

Region: City of Copenhagen, Denmark

Taxon: Anopheles, Aedes

Type: undefined

Why is this important: First ever records

Priority: medium

Comments: This is test. delete

Dataholders contact information: dschigel@gbif.org

Users contact info: dschigel

**Comment by dschigel** [comment]
Delete this test
