### ISSUE TITLE
Biodiversity loss by country 2020

### ISSUE THREAD

**Issue by gbif-portal** [gbif/data-mobilization#220]
## Biodiversity loss by country 2020

Region: Worldwide

Taxon: pérdida de biodiversidad

Why is this important: Estoy buscando el indicador para ver la pérdida de biodiversidad por países y así saber cada país cuanto está afectando a esa pérdida global.

Priority: low

License: Not open

Users contact info: colmos@foretica.es

**Comment by CecSve** [comment]
Not a dataset suggestion. Will close.
