### ISSUE TITLE
Radhika balachandran

### ISSUE THREAD

**Issue by gbif-portal** [gbif/data-mobilization#230]
## Radhika balachandran

Dataset link: gbif

Region: Kerala

Taxon: nemipterus

Type: occurrence

Why is this important: for thesis work

License: Not open

Dataholders contact information: radhikabalachandran7@gmail.com

Users contact info: radhikabalachandran7@gmail.com

**Comment by CecSve** [comment]
Does not appear to be a dataset suggestion - will close.
