### ISSUE TITLE
All-Russian Collection of Microorganisms (VKM)

### ISSUE THREAD

**Issue by gbif-portal** [gbif/data-mobilization#236]
## All-Russian Collection of Microorganisms (VKM)

Dataset link: www.vkm.ru

Region: Former USSR

Taxon: microorganisms

Type: occurrence

Why is this important: The preservation of microorganisms in culture collections and the provision of information about them is the basis of applied microbiology and biotechnology, as it allows obtaining data on potential producers of various biologically active substances.

Priority: medium

License: Not open

Dataholders contact information: smovkm@gmail.com

Users contact info: smovkm@gmail.com

**Comment by CecSve** [comment]
Dataset is in GBIF: https://www.gbif.org/dataset/b3e4cecc-7554-419d-a336-1218548370d4
