### ISSUE TITLE
zoonotic pathogens data

### ISSUE THREAD

**Issue by gbif-portal** [gbif/data-mobilization#254]
## zoonotic pathogens data

Region: Global

Taxon: Viruses, bacteria, Fungi, Protozoa, Chromista, Archaea

Why is this important: This data can be used in predicting spillover events and informing policy makers,... to stop any potential endemic/pandemic

Priority: high

**Comment by dschigel** [comment]
Insuffcient level of detail to follow up, too general, no concrete target identified
