### ISSUE TITLE
Russian red book fungi

### ISSUE THREAD

**Issue by gbif-portal** [gbif/data-mobilization#257]
## Russian red book fungi

Dataset link: http://www.vkm.ru

Region: Russia

Taxon: Fungi

Type: checklist

Why is this important: For the first time, data on the taxonomic diversity of specially protected fungi in the territory of the Russian Federation are presented.

Priority: high

Dataholders contact information: smovkm@gmail.com

Users contact info: smovkm@gmail.com

**Comment by CecSve** [comment]
Dataset is now on GBIF: https://www.gbif.org/dataset/cd63e40f-1726-4b78-bb2c-9458f4eef3d6
