### ISSUE TITLE
Geographical distribution of American cutaneous leishmaniasis and its phlebotomine vectors (Diptera: Psychodidae) in the state of São Paulo, Brazil

### ISSUE THREAD

**Issue by gbif-portal** [gbif/data-mobilization#258]
## Geographical distribution of American cutaneous leishmaniasis and its phlebotomine vectors (Diptera: Psychodidae) in the state of São Paulo, Brazil

Dataset link: 10.1186/1756-3305-3-121

Region: Brazil, São Paulo state

Taxon: Phlebotominae

Type: occurrence

Why is this important: Records from1943 to 2009 of sand flies collected in São Paulo state..

Priority: medium

License: CC-BY-NC 4.0

Bibliographic reference: https://parasitesandvectors.biomedcentral.com/articles/10.1186/1756-3305-3-121

Dataholders contact information: paloma.helena @fiocruz.br

Users contact info: paloma.helena@fiocruz.br

**Comment by CaroleSinou** [comment]
As indicated in the paper, the database is available upon request to Paloma Helena Fernandes Shimabukuro (1st author).
I've contacted her, explaining the thematic helpdesk and how I can help.
I will also contact the Brazilian node when/if I receive an answer.

**Comment by CaroleSinou** [comment]
I'm working with Paloma  to publish data from this paper.

**Comment by CaroleSinou** [comment]
The dataset has been standardized to Darwin Core and enhanced with temporal and geographical information, when available.
It will be published soon on the Fiocruz IPT (https://www.gbif.org/installation/9b51fa83-7d7e-4ccc-acc4-1879f9d8dd6d).
These occurrences are not part of the recently published dataset 'Fiocruz/COLFLEB - Coleção de Flebotomíneos' (https://www.gbif.org/dataset/2a629a9a-38d1-496b-afbf-b4ff3b8fae60)

**Comment by pshimabukuro** [comment]
Dataset published.
https://www.gbif.org/dataset/9944a089-0dad-4c37-9e28-b51a18401955
