### ISSUE TITLE
brown pelican

### ISSUE THREAD

**Issue by gbif-portal** [gbif/data-mobilization#263]
## brown pelican

Region: atlantic

Taxon: bird

**Comment by ManonGros** [comment]
It looks like the person who logged the suggestion didn't know they had to use the scientific name in their search.
There is around a million records of brown pelicans in the Atlantic: https://www.gbif.org/occurrence/map?taxon_key=5229158&geometry=POLYGON((-75.67383%2042.36328,-81.47461%2034.18945,-86.30859%2032.60742,-97.4707%2032.51953,-99.93164%2023.99414,-97.03125%2018.01758,-90.43945%2018.36914,-87.71484%2014.41406,-83.75977%2012.65625,-82.88086%208.87695,-74.0918%208.08594,-47.63672%202.28516,-51.07908%2054.76645,-62.32252%2053.19478,-75.67383%2042.36328))&occurrence_status=present
