### ISSUE TITLE
Dataset of herbarium specimens of threatened vascular plants in Catalonia

### ISSUE THREAD

**Issue by dnoesgaard** [gbif/data-mobilization#29]
Data paper with ipt dataset not registered with GBIF

http://phytokeys.pensoft.net/articles.php?id=11542

http://www.gbif.es/ipt/resource?r=threatenedCAT

this deserves some attention I think...

**Comment by kbraak** [comment]
@santiagomtzdelariva can you please help with this issue? We are wondering if the publishers plan to share this dataset through GBIF? Also, is there a reason GBIF Spain never minted this dataset a DOI? A DOI is a persistent identifier whereas the URL may change, hence why it is preferable to use a DOI for linking to a dataset. Thanks for your assistance, Kyle

<img width="538" alt="screen shot 2017-03-07 at 17 00 51" src="https://cloud.githubusercontent.com/assets/5981100/23665106/d37b0ec8-0357-11e7-982a-2db667c2f146.png">

**Comment by ahahn-gbif** [comment]
https://www.gbif.org/dataset/dbc709b9-e36e-4dd7-ab5b-c3cb08c2779d
