### ISSUE TITLE
Mushroom diversity in Lumle (Kaski) and study of Clavariales from Lumle and vicinity of Kathmandu valley, Nepal

### ISSUE THREAD

**Issue by gbif-portal** [gbif/data-mobilization#324]
## Mushroom diversity in Lumle (Kaski), Nepal

Dataset link: https://lib.icimod.org/record/333

Region: Kathmandu, Nepal

Taxon: Mushrooms, Clavariales

Type: occurrence

Priority: medium

Dataholders contact information: shiva.devkota@gmail.com

Users contact info: lshrestha@gbif.org

**Comment by lilee-sh** [comment]
Author contacted and have agreed to share the data.

**Comment by lilee-sh** [comment]
Data preparation in progress

**Comment by lilee-sh** [comment]
Dataset published: https://www.gbif.org/dataset/b5b20a59-967a-449d-9616-0342ed17dee9
