### ISSUE TITLE
"Zaprudyanskyi" general zoological reserve

### ISSUE THREAD

**Issue by gbif-portal** [gbif/data-mobilization#337]
## &quot;Zaprudyanskyi&quot; general zoological reserve

Dataset link: https://www.inaturalist.org/projects/zaprudyanskyi-general-zoological-reserve

Region: Ukraine

Taxon: Protist mushrooms plants shellfish insects reptiles birds mammals other animals arachnids amphibians

Priority: medium

License: CC0 1.0

Users contact info: maria.izhokina@gmail.com

**Comment by ManonGros** [comment]
Contacted the person who made the suggestion by email to let them know that all the research-grade iNaturalist observations that are shared under http://creativecommons.org/publicdomain/zero/1.0/, http://creativecommons.org/licenses/by/4.0/ or http://creativecommons.org/licenses/by-nc/4.0/ will be automatically shared on GBIF by iNaturalist. For more information, you they can check [this page](https://www.gbif.org/dataset/50c9509d-22c7-4a22-a47d-8c48425ef4a7).
