### ISSUE TITLE
Disbribución del Tamandua tetradactyla en La Rioja, Argentina

### ISSUE THREAD

**Issue by gbif-portal** [gbif/data-mobilization#350]
## Disbribución del Tamandua tetradactyla en La Rioja, Argentina

Dataset link: https://www.inaturalist.org/observations?place_id=10420&amp;subview=table&amp;taxon_id=47104

Region: La Rioja, Argentina

Taxon: Tamandua tetradactyla

Type: occurrence

Why is this important: distribución y hallazgos de Tamandua tetradactyla en la provincia de la rioja argentina.

Priority: high

License: Unspecified

Bibliographic reference: Agüero, J.A., Díaz, J.V. and González, D. 2003. Presencia y características del hábitat asociadas a Tamandua tetradactyla en las Sierras de los Llanos de La Rioja, Argentina. In: SAREM (ed.), XVIII Jornadas Argentinas de Mastozoología, pp. 81. La Rioja, Argentina.

Dataholders contact information: prof.diego.gonzalez@gmail.com

Users contact info: Diego Sebastián González

**Comment by ManonGros** [comment]
Replied by email explaining how the iNaturalist data are automatically shared on GBIF.
