### ISSUE TITLE
A new species of Stenasellus Dollfus, 1897 from Iran, with a key to the western Asian species (Crustacea, Isopoda, Stenasellidae)

### ISSUE THREAD

**Issue by gbif-portal** [gbif/data-mobilization#357]
## A new species of Stenasellus Dollfus, 1897 from Iran, with a key to the western Asian species (Crustacea, Isopoda, Stenasellidae)

Dataset link: https://zookeys.pensoft.net/articles.php?id=23239

Region: IRAN

Taxon: Stenasellus tashanicus

Type: occurrence

Why is this important: No pointed locality of this species on the GBIF map

Priority: high

Bibliographic reference: 30°51&#39;54&quot;N, 50°10&#39;29&quot;E

Dataholders contact information: javad.malek@zrc-sazu.si

Users contact info: javad.malek@zrc-sazu.si

**Comment by ManonGros** [comment]
It looks like this dataset is already in GBIF via PLAZI: https://www.gbif.org/dataset/d7215e5f-5a23-429d-8a32-c1ce8da7c0cb
Will contact the user to let them know.
