### ISSUE TITLE
Amphibians and reptiles from the Natural History Museum, Tribhuvan university, Nepal

### ISSUE THREAD

**Issue by gbif-portal** [gbif/data-mobilization#362]
## Amphibians and reptiles from the Natural History Museum, Tribhuvan university, Nepal

Region: Nepal

Taxon: Amphibia and Reptilia

Type: occurrence

Why is this important: This will be a first dataset on occurrences of Amphibia and Reptilia from the collection of Natural History Museum of Nepal.

Priority: high

Dataholders contact information: ganeshbdr13@gmail.com

Users contact info: lshrestha@gbif.org

**Comment by lilee-sh** [comment]
- This dataset is from a GRSciColl institution: https://www.gbif.org/grscicoll/institution/3448c872-18f9-4d70-8237-148cd1d87b3f
- The institution has been contacted and they have agreed to share their specimen data through GBIF.

**Comment by lilee-sh** [comment]
Dataset published: https://www.gbif.org/dataset/b10f3fb8-d6f1-400a-9d73-140ac194ea6d
