### ISSUE TITLE
Omalocephala cincta

### ISSUE THREAD

**Issue by gbif-portal** [gbif/data-mobilization#366]
## Omalocephala cincta

Dataset link: https://www.inaturalist.org/observations/36103591

Region: Africa

Taxon: Lepidoptera

Type: occurrence

Why is this important: it&#39;s rarity

Priority: medium

Bibliographic reference: https://www.biodiversitylibrary.org/item/25015#page/42/mode/1up

Dataholders contact information: karim241267@yahoo.fr

Users contact info: karim241267@yahoo.fr

**Comment by ManonGros** [comment]
The record is already on GBIF: https://www.gbif.org/occurrence/3079732681, I will contact the user to let him know.
