### ISSUE TITLE
Lichenized fungi

### ISSUE THREAD

**Issue by gbif-portal** [gbif/data-mobilization#384]
## Lichenized fungi

Region: Bulgaria mainly, and parts of Eurasia

Taxon: Ascomycota

Type: occurrence

Priority: medium

License: CC0 1.0

Comments: The dataset is from this collection which is already digitized, without photos, but needs some cleaning: https://scientific-collections.gbif.org/collection/0b347ac9-5b02-434a-b562-c48507a32243

Dataholders contact information: salza.palpurina@gmail.com

Users contact info: spalpurina@gbif.org

**Comment by spalp** [comment]
- Still in process of cleaning

**Comment by spalp** [comment]
Published: https://www.gbif.org/dataset/eb826c4e-1bcb-4978-8f7b-26d8f1f58134
