### ISSUE TITLE
Into the Okavango

### ISSUE THREAD

**Issue by gbif-portal** [gbif/data-mobilization#39]
## Into the Okavango

Dataset link: https://intotheokavango.org/data

Region: Okavango Delta, Nigeria

Taxon: All?

Type: occurrence

Why is this important: Seemingly open-access data from expeditions and transects in Nigeria&#39;s Okavango Delta. GBIF-mediated data is scant in this region.

Priority: medium

License: Unspecified

Bibliographic reference: https://www.theguardian.com/environment/radical-conservation/2015/may/28/expedition-source-okavango-delta

Comments: Not clear how the data is structured, as the website conflates various kinds of information. However, it does appear that the raw materials for observations are present.

Dataholders contact information: ? https://ocr.nyc/contact

Users contact info: kcopas@gbif.org

**Comment by kbraak** [comment]
@kcopas should this not be the Okavango Delta in Botswana? Actually, we have a [BID project](https://demo.gbif.org/project/bid/africa/2015/data-rescue-botswana-wildlife-management-association) involving the Okavango Research Institute and the [Botswana Wildlife Management Association](http://www.gbif.org/publisher/bd14512a-b63d-42c1-b426-4c4f0623b6c3). Surely it would be good to coordinate the mobilization of this data together with them.

**Comment by kcopas** [comment]
Yes, that one, too! Seriously, thanks @kbraak—moving a little too manically through my scattered notes, business cards and browser tabs…

**Comment by kcopas** [comment]
[Twitter](https://twitter.com/DavidGoyder/status/722066989439561731) is blowing up about the potential for latest expedition in this initiative to fill gaps in GBIF-mediated data. If it rises in priority, not possible Kew connection.

[See also #Cuito2016 >](https://twitter.com/hashtag/Cuito2016?src=hash)

**Comment by CecSve** [comment]
@kcopas and @ahahn-gbif is it correctly understood that there might be data associated with [this project](https://www.nationalgeographic.org/projects/okavango/) that is not already registered in other resources (e.g. [this](https://www.gbif.org/project/82758/data-rescue-for-the-records-of-the-botswana-wildlife-management-association#datasets), [this](https://www.gbif.org/dataset/search?q=Okavango%20delta), and [this](https://www.gbif.org/dataset/search?publishing_org=02b89818-33ab-4bf7-984d-f88a8e0b0b0f)) and what we need is for someone to look into it?

**Comment by kcopas** [comment]
On many of these old issues, looking at the dates will probably provide clues.

It appears the issue was created before any of the datasets arrived, and we’ve established multiple data mobilization connections and added data across multiple taxonomic groups. While there's always more data out there, I think we could safely say the issue's been addressed.

=====
Kyle Copas
GBIF Secretariat
+45 28 75 14 75

Sent from my iPhone: thumbs don’t fejl mig nu
________________________________
