### ISSUE TITLE
Diat.barcode library

### ISSUE THREAD

**Issue by gbif-portal** [gbif/data-mobilization#393]
## Diat.barcode library

Dataset link: https://doi.org/10.1038/s41598-019-51500-6

Region: West Antarctic Peninsula (or global)

Taxon: diatoms

Type: checklist

Why is this important: Diatoms OTUs

Priority: medium

License: Unspecified

Bibliographic reference: https://mbmg.pensoft.net/article/110194/

Users contact info: dschigel

**Comment by tobiasgf** [comment]
same as issue #331 ?

**Comment by sformel-usgs** [comment]
I've added the details here to #331 and closing this issue.
