### ISSUE TITLE
Echeveria andreae inaturalist observation

### ISSUE THREAD

**Issue by gbif-portal** [gbif/data-mobilization#396]
## Echeveria andreae inaturalist observation

Dataset link: https://www.inaturalist.org/observations/29938938

Region: Oaxaca, Mexico

Taxon: Crassulaceae

Type: occurrence

Priority: high

**Comment by sformel-usgs** [comment]
Hi @kueda!  I'm the US node manager for GBIF, and I try to follow up on the issues and datasets flagged in github.  I hope you don't' mind me pulling you in here. 

I'm having trouble identifying why this occurrence isn't published to GBIF. As far as I can tell, it is research grade and under a CC-BY license. I couldn't see the timestamp on the research grade, so it's possible I just need to be patient.  Could you take a look when you have a moment?

**Comment by ManonGros** [comment]
Hi @sformel-usgs the problem is that the license used isn't an open license, it is CC BY-SA 4.0 DEED. The data should be under:
1) http://creativecommons.org/publicdomain/zero/1.0/,
2) http://creativecommons.org/licenses/by/4.0/,
3) http://creativecommons.org/licenses/by-nc/4.0/

**Comment by sformel-usgs** [comment]
Thanks @ManonGros. How did you figue this out? The [inaturalist image](https://www.inaturalist.org/photos/46751634) link leads to the second license you mention (https://creativecommons.org/licenses/by/4.0/) which is why I was confused.  Is the occurrence license differently from the image?

**Comment by sformel-usgs** [comment]
Ah...I found it, just had to look a little harder. My apologies, I didn't realize the pictures and observations could have difference licenses applied.

**Comment by kueda** [comment]
Yeah, sorry about that. The different license thing is a constant source of
confusion that we should probably ditch.

**Comment by timhirsch** [comment]
Before ditching... we would want to be sure this does not deter iNat users from apply a record licence compatible with GBIF sharing if they were not able to apply a stricter licence on their photos #unintendedconsequences.
