### ISSUE TITLE
Pisces collection from the Natural History Museum, Tribhuvan University, Nepal

### ISSUE THREAD

**Issue by gbif-portal** [gbif/data-mobilization#398]
## Pisces collection from the Natural History Museum, Tribhuvan University, Nepal

Region: Nepal

Taxon: Pisces

Type: occurrence

Why is this important: This will be a first dataset on occurrences of Pisces from the collection of Natural History Museum of Nepal

Priority: high

Dataholders contact information: ganeshbdr13@gmail.com

Users contact info: lshrestha@gbif.org

**Comment by lilee-sh** [comment]
- This dataset is from a GRSciColl institution: https://www.gbif.org/grscicoll/institution/3448c872-18f9-4d70-8237-148cd1d87b3f
- The dataset is under preparation

**Comment by lilee-sh** [comment]
- Dataset published: https://www.gbif.org/dataset/21626145-8f6d-43c1-aa20-804ad65bba91/metrics
