### ISSUE TITLE
An annotated checklist of the birds in Loharghat Forest Range, Assam, India

### ISSUE THREAD

**Issue by gbif-portal** [gbif/data-mobilization#413]
## An annotated checklist of the birds in Loharghat Forest Range, Assam, India

Dataset link: https://threatenedtaxa.org/index.php/JoTT/article/view/8638/9692

Region: Loharghat, Assam, India

Taxon: Birds

Type: occurrence

Why is this important: Detailed study of a specific place

Priority: low

License: Unspecified

Bibliographic reference: https://doi.org/10.11609/jott.8638.16.1.24568-24583

Dataholders contact information: leons@aaranyak.org

Users contact info: vbarve@gbif.org

**Comment by vijaybarve** [comment]
Contacting the authors

**Comment by vijaybarve** [comment]
Authors are on board and have requested endorsement for data publisher.

**Comment by vijaybarve** [comment]
Data publisher endorsement received. Working on data.

**Comment by vijaybarve** [comment]
Dataset published https://www.gbif.org/dataset/d66deccd-c506-49f4-8c34-3ca886125794
