### ISSUE TITLE
Mammals collection from the Natural History Museum, Tribhuvan University, Nepal

### ISSUE THREAD

**Issue by gbif-portal** [gbif/data-mobilization#420]
## Mammals collection from the Natural History Museum, Tribhuvan University, Nepal

Region: Nepal

Taxon: Mammals

Type: occurrence

Why is this important: This will be a first dataset on occurrences of Pisces from the collection of Natural History Museum of Nepal

Priority: high

Dataholders contact information: ganeshbdr13@gmail.com

Users contact info: lshrestha@gbif.org

**Comment by lilee-sh** [comment]
Dataset in progress

**Comment by lilee-sh** [comment]
Dataset published: https://www.gbif.org/dataset/8da6980a-7ebb-456c-94eb-5f6086de6570
