### ISSUE TITLE
Gymnosperm collection from the Natural History Museum, Tribhuvan University, Nepal

### ISSUE THREAD

**Issue by gbif-portal** [gbif/data-mobilization#426]
## Gymnosperm collection from the Natural History Museum, Tribhuvan University, Nepal

Region: Nepal

Taxon: Gymnosperm

Type: occurrence

Why is this important: This will be a first dataset on occurrences of gymnosperm from the collection of Natural History Museum of Nepal

Priority: medium

Dataholders contact information: ganeshbdr13@gmail.com

Users contact info: lshrestha@gbif.org

**Comment by lilee-sh** [comment]
Dataset published: https://www.gbif.org/dataset/867c6efe-b7c6-4201-b8b2-1bd33737920b
