### ISSUE TITLE
Bryophytes collection from the Natural History Museum, Tribhuvan University, Nepal

### ISSUE THREAD

**Issue by gbif-portal** [gbif/data-mobilization#427]
## Bryophytes collection from the Natural History Museum, Tribhuvan University, Nepal

Region: Nepal

Taxon: Bryophyta

Type: occurrence

Why is this important: This will be a first dataset on occurrences of Pteridophytes from the collection of Natural History Museum of Nepal

Priority: medium

Dataholders contact information: ganeshbdr13@gmail.com

Users contact info: lshrestha@gbif.org

**Comment by lilee-sh** [comment]
Dataset in progress

**Comment by lilee-sh** [comment]
Dataset published: https://www.gbif.org/dataset/661b954a-9f4e-453d-b122-1ec18a3ad955
