### ISSUE TITLE
Rangeland vegetation in Olangchung Gola, Eastern Himalaya, Nepal

### ISSUE THREAD

**Issue by gbif-portal** [gbif/data-mobilization#429]
## Rangeland vegetation in Olangchung Gola, Eastern Himalaya, Nepal

Dataset link: https://lib.icimod.org/record/34748

Region: Eastern Nepal

Taxon: Plant species

Type: occurrence

Why is this important: This dataset contains occurrences of rangeland vegetation above 3750 meters above sea level.

Priority: medium

Dataholders contact information: dineshbhuju@gmail.com

Users contact info: lshrestha@gbif.org

**Comment by lilee-sh** [comment]
- The datasets is in progress

**Comment by lilee-sh** [comment]
Dataset published: https://www.gbif.org/dataset/c6111dca-8230-4e8f-90c3-4a5f01f9644f
