### ISSUE TITLE
iNaturalist

### ISSUE THREAD

**Issue by gbif-portal** [gbif/data-mobilization#440]
## iNaturalist

Dataset link: https://www.inaturalist.org/taxa/1178670-Braunilla

Region: South America

Taxon: Braunilla Wasbauer &amp; Kimsey, 2019

Type: occurrence

Priority: low

License: Unspecified

**Comment by CecSve** [comment]
There are currently four observations for this genus in iNaturalist: https://www.inaturalist.org/observations?verifiable=true&taxon_id=1178670. None of the observations are research grade yet, so they are not shared with GBIF. There is no contact information for the issue provider, so I will close the issue without being able to alert the original submitter.
