### ISSUE TITLE
BOLD BIN numbers

### ISSUE THREAD

**Issue by gbif-portal** [gbif/data-mobilization#45]
## BOLD BIN numbers

Dataset link: http://www.boldsystems.org/index.php/Public_BarcodeIndexNumber_Home

Region: global

Taxon: life

Type: checklist

Why is this important: BOLD BIN numbers should be added to the GBIF backbone at some stage for better integration with sequence data. This requires the BIN numbers to be published to GBIF

License: Unspecified

Comments: ChecklistBank and NameParser should be ready to index BIN numbers as dwc:scientificName

**Comment by dschigel** [comment]
We seem to have it https://demo.gbif.org/dataset/4cec8fef-f129-4966-89b7-4f8439aba058

**Comment by mdoering** [comment]
Ah, true. Rod Page created this static copy. It would be much better if BOLD themselves would publish it regularly though

**Comment by mdoering** [comment]
This BOLD dataset uses the BIN numbers only as taxonID, but not as the scientificName.
That wont work nicely when building a backbone as the many redundant names will get conflated into a single name - when we actually would like all those unique BIN numbers to be included.

We could ask Rod to republish it.

**Comment by dschigel** [comment]
Let us ask then, @rdmpage :). Rod, we still need reattribute both this BINs and the BOLD occurrence datasets you published to IBOL, but this should not prevent us from making new improved versions.

**Comment by rdmpage** [comment]
@dschigel @mdoering I'm on holiday for the next two weeks but can look into this when I get back. @dschigel Regarding "reattribution" actually I don't think we should do that. IBOL have done nothing towards publishing this data, if they want attribution then they should publish it themselves. Otherwise what's the incentive for them to invest any effort in sending the data to GBIF if they get it done for them. @mdoering So I guess you'd like the BOLD BIN code appended to the name of species that lack species-level names?

**Comment by mdoering** [comment]
@rdmpage We were thinking of using the BIN numbers as the scientificName, basically the label of the taxon. We do this already for Fungal Species Hypothesis: http://www.gbif-uat.org/species/search?dataset_key=87904172-8516-4150-877c-bf58b8cb74f3&name_type=DOUBTFUL

I am adding a new name type = OTU so one can filter out these kind of "names" properly.
In case there are both a latin name and a BIN number we might want to separate them and treat the BIN as a synonym for the latin name. Having them as taxonID makes perfect sense, but hides them from most of the GBIF portal and our internal processing, e.g. backbone building. It would be great to see them more prominently as yet another label for a taxon.

Makes sense?

**Comment by rdmpage** [comment]
@mdoering Yes, makes sense. I'd like to check for BOLD taxa in GBIF's version of the NCBI taxonomy as it would make sense to link those as synonyms. I'd also need to rebuild the iBOL occurrence data set.

**Comment by rdmpage** [comment]
@mdoering @dschigel OK, I've found some time to look at the barcodes again. 

Is this what you have in mind? If there's a scientific name we have two rows, one with the name (and arbitrary identifier), the second row has the BOLD BIN number as the **taxonID** , which is linked to the name via **acceptedNameUsageID**. If we don't have a proper scientific name, then we have one row with the **scientificName** and the **taxonID** both set to the BOLD BIN.

| taxonID | acceptedNameUsageID | phylum | class | order | family| subfamily | genus | specificEpithet | infraspecificEpithet | scientificName| taxonRemarks | references |
|:-----|:-----|:-----|:-----|:-----|:-----|:-----|:-----|:-----|:-----|:-----|:-----|:-----|
|1||Chordata|Mammalia|Soricomorpha|Soricidae|Soricinae|Sorex|cinereus||Sorex cinereus||http://www.boldsystems.org/index.php/Public_BarcodeCluster?clusteruri=BOLD:AAA1224|
|BOLD:AAA1224|1||||||||||||
|BOLD:AAB0530||Chordata|Mammalia|Soricomorpha|Soricidae|Soricinae|Sorex|||BOLD:AAB0530|Sorex arcticus;Sorex cinereus|http://www.boldsystems.org/index.php/Public_BarcodeCluster?clusteruri=BOLD:AAB0530|

**Comment by mdoering** [comment]
Hi Rod, pretty much, yes. Just add BOLD:AAA1224 also as the scientificName in row 2

**Comment by rdmpage** [comment]
@mdoering OK, will do. Once I've done this I'll update the dataset and get GBIF to crawl it.

**Comment by rdmpage** [comment]
@mdoering Dataset rebuilt and in github, which is the endpoint. I've made an API call for it to be crawled.

**Comment by mdoering** [comment]
Excellent, sth went wrong with our network today so I started another indexing round just now

**Comment by ahahn-gbif** [comment]
I assume we consider this done - please reopen if there is any work still outstanding on this
