### ISSUE TITLE
Angiosperm specimens preserved at NHM, TU, Nepal

### ISSUE THREAD

**Issue by gbif-portal** [gbif/data-mobilization#460]
## Angiosperm specimens preserved at NHM, TU, Nepal

Region: Nepal

Taxon: Angiosperm

Type: occurrence

Why is this important: This will be a first dataset on occurrences of Angiosperms from the collection of Natural History Museum of Nepal

Priority: medium

Dataholders contact information: ganeshbdr13@gmail.com

Users contact info: lshrestha@gbif.org

**Comment by lilee-sh** [comment]
Dataset published https://www.gbif.org/dataset/a2b36e77-a641-496b-8844-eb3e225abe0f
