### ISSUE TITLE
Early Land Plants Today

### ISSUE THREAD

**Issue by gbif-portal** [gbif/data-mobilization#54]
## Eearly Land Plants Today

Dataset link: http://elpt.fieldmuseum.org/

Region: global

Taxon: Marchantiophyta &amp; Anthocerotophyta

Type: checklist

Priority: medium

Dataholders contact information: Matt von Konrat [mvonkonrat@fieldmuseum.org] Anders Hagborg [hagborg@pobox.com] Lars Söderström [lars.soderstrom@ntnu.no]

**Comment by ahahn-gbif** [comment]
We do not have any published checklist from the Field Museum so far (https://www.gbif.org/dataset/search?publishing_org=7b8aff00-a9f8-11d8-944b-b8a03c50a862).

**Comment by CecSve** [comment]
Seems to have be published to GBIF: https://www.gbif.org/dataset/fc02edbb-2c18-4672-8d3d-5722c95a0827 will close.
