### ISSUE TITLE
PollardBase

### ISSUE THREAD

**Issue by gbif-portal** [gbif/data-mobilization#62]
## PollardBase

Dataset link: http://www.pollardbase.org

Region: Selected U.S. states

Taxon: Lepidoptera

Type: sampling event

Why is this important: Standardized data entry and management system for state butterfly monitoring programs that follows &quot;Pollard walk&quot; survey protocols

Priority: medium

License: Unspecified

Comments: Linked to follow up item from 2017 Citizen Science Association conference: @dschigel ?

Dataholders contact information: Leslie.Ries@georgetown.edu

Users contact info: @kcopas

**Comment by kbraak** [comment]
Great Kyle, they can take advantage of the data model developed for systematic butterfly monitoring scheme data described here: http://gbif.blogspot.dk/2017/01/sampling-event-standard-takes-flight-on.html

**Comment by ahahn-gbif** [comment]
Published June 2018: https://www.gbif.org/dataset/6dc35c87-ff97-4708-9e45-6f764ddc1ef3 - closing
