### ISSUE TITLE
Biodiversidad de Huertas Urbanas en el Valle de Sibundoy, Putumayo, Colombia

### ISSUE THREAD

**Issue by gbif-portal** [gbif/data-mobilization#69]
## Biodiversidad de Huertas Urbanas en el Valle de Sibundoy, Putumayo, Colombia

Dataset link: http://ipt.biodiversidad.co/sib/resource?r=itp-1

Region: Valle de Sibundoy, Putumayo, Colombia

Taxon: Plantae

Type: checklist

Why is this important: Presenta la biodiversidad vegetal cultivada en huertas urbanas en el municipio del Valle de Sibundoy, departamento del Putumayo, Colombia

Priority: low

License: CC0 1.0

Dataholders contact information: aguerra@itp.edu.co

Users contact info: pablo.moreno@itp.edu.co

**Comment by kcopas** [comment]
Thanks for submitting this, Pablo. All that needs to happen, however, is to register the dataset for publication on GBIF.org. 

See [Registro GBIF](http://ipt.biodiversidad.co/sib/resource?r=itp-1#gbif): 
> Este recurso no ha sido registrado en GBIF

**Comment by ahahn-gbif** [comment]
Published since July 2017, closing
