### ISSUE TITLE
AMBON: Arctic Marine Biodiversity Observation Network,

### ISSUE THREAD

**Issue by gbif-portal** [gbif/data-mobilization#71]
## AMBON: Arctic Marine Biodiversity Observation Network,

Dataset link: https://mbon.ioos.us/#module-search?page=1&amp;tagId=Tag%3AAMBON+Projects&amp;q=&amp;tags=Tag%3AAMBON+Projects&amp;types=module%2Csensor_station%2Cproject

Region: Marine Arctic

Taxon: All marine taxa

Type: undefined

Why is this important: Both marine and Arctic environments are under sampled. Various datasets organized taxonomically seem available. First collections were made during an Aug-Sep 2015 cruise, second cruise about to get underway.

Priority: high

License: Unspecified

Bibliographic reference: http://www.knom.org/wp/blog/2017/08/04/marine-scientists-depart-nome-to-study-chukchi-sea-biodiversity/

Comments: Data should be open based on US federal and NSF funding. Strong project connections with University of Alaska Fairbanks, host for GBIF power users/allies Derek Sikes &amp; Faulk Heuttmann.

Users contact info: @kcopas

**Comment by albenson-usgs** [comment]
Some of these have been made available but not all.
https://www.gbif.org/dataset/f4b56e69-4ff5-4cd2-bc48-ec273232d9e0
https://www.gbif.org/dataset/07be324e-bcf5-4e83-b9cc-dc2a962fba30
https://www.gbif.org/dataset/d021ed3a-7179-4f25-bfd3-90d72cc6fd38
https://www.gbif.org/dataset/b6e61b53-a471-4e5a-8378-6920a5a0275d
https://www.gbif.org/dataset/bcaf91ed-a49f-4e34-8a20-fe8457986921
