### ISSUE TITLE
IOOS Data Catalog

### ISSUE THREAD

**Issue by gbif-portal** [gbif/data-mobilization#72]
## IOOS Data Catalog

Dataset link: https://mbon.ioos.us

Region: Marine

Taxon: All marine taxa

Type: undefined

Why is this important: Undersampled environment. Many different datasets. Connected to GEO BON. Probably should assess current overlap (if any) with help of OBIS.

Priority: medium

License: Unspecified

Users contact info: @kcopas

**Comment by albenson-usgs** [comment]
I'm already sharing all the data possible from the MBON portal. I work closely with IOOS on biological data management and have conducted several trainings for the IOOS Regional Associations to help them with aligning their biological data to Darwin Core.
