### ISSUE TITLE
New York Humpback Whale Catalog

### ISSUE THREAD

**Issue by gbif-portal** [gbif/data-mobilization#74]
## New York Humpback Whale Catalog

Dataset link: https://www.gothamwhale.org/flukes.html

Region: Waters off New York City

Taxon: Megaptera novaeangliae

Type: occurrence

Why is this important: Relatively high-profile citizen science project that&#39;s emerged in recent years. Regular whale-watching cruises are generating a photo-based fluke catalog of humpback whales off the coast of New York City, where the population of &#39;the urban whale&#39; appears to be recovering. Not that we would see that from [the current data available for the region](https://demo.gbif.org/occurrence/gallery?has_coordinate=true&amp;has_geospatial_issue=false&amp;taxon_key=8931210&amp;advanced=1&amp;geometry=POLYGON((-75.10725363274841%2043.435195687012914,-75.10725363274841%2039.435195687012914,-71.10725363274841%2039.435195687012914,-71.10725363274841%2043.435195687012914,-75.10725363274841%2043.435195687012914))).

Priority: medium

License: Unspecified

Bibliographic reference: https://www.theringer.com/2017/7/12/16077852/new-york-city-gotham-whales-coastline-f7acc7b50b6e

Comments: **Note** the other similar fluke catalogs are listed on the page above:
+ Coastal Research and Education Society of Long Island
+ Allied Whale, College of the Atlantic, in Maine
+ The Provincetown Center for Coastal Studies
+ Whales Bermuda
+ Nature Tropicale, Benin, W. Africa

Dataholders contact information: [Paul Sieswerda](paul@gothamwhale.org)

Users contact info: @kcopas

**Comment by CecSve** [comment]
New link: https://gothamwhale.org/ - fluke catalouge not active anymore?

**Comment by kcopas** [comment]
Bummer. Looks like they've gone another direction with the data side of life:

>  As thanks for taking part in this crucial work, you will get a coupon for a free beer with every validated entry. More than 10 validated contributions earns a Gotham Whale T-shirt.
