### ISSUE TITLE
Systema Dipterorum

### ISSUE THREAD

**Issue by gbif-portal** [gbif/data-mobilization#78]
## Systema Dipterorum

Dataset link: http://www.diptera.org/

Region: Global

Taxon: Diptera

Type: checklist

Why is this important: It is the nomenclatural authority for all Diptera which are 12% of all species and missing in ZooBank

Priority: high

License: Unspecified

Comments: The dataset is supported by GBIF and Thomas next door

Dataholders contact information: Thomas Pape, tpape@snm.ku.dk

Users contact info: mdoering@gbif.org

**Comment by ahahn-gbif** [comment]
Hi @thomasstjerne, would you have any time to take a look at this and advise whether the suggestion is still valid and would merit follow-up? Many thanks!

**Comment by thomasstjerne** [comment]
This has been addressed in COL: https://github.com/CatalogueOfLife/data/issues/194
