### ISSUE TITLE
NCSU Insect Museum

### ISSUE THREAD

**Issue by gbif-portal** [gbif/data-mobilization#79]
## NCSU Insect Museum

Dataset link: http://specimens.insectmuseum.org/public/specimen

Region: Southeastern US, Caribbean, but global holdings in some

Taxon: Caribbean Auchenorrhyncha ([72,600 new accessions](https://twitter.com/ncsuinsects/status/905791456195072001)), Lepidoptera, Acari, Anthophila (the bees), Diptera, Coleoptera, Heteroptera, Orthoptera, Collembola

Type: occurrence

Why is this important: The NC State University Insect Museum is an internationally recognized resource for the study of insects and mites from North Carolina, the Southeastern United States, and, in several insect groups, the world. New accession of Caribbean Auchenorrhyncha specimens cover major geographic and taxonomic gaps for current GBIF-mediated data. Our holdings are partitioned into four main collections: - NC State University Insect Collection - the vast majority of our specimens are housed in the research collection. Drawers can be browsed virtually through our GigaPan user profile. - Genome Bank - our cold storage collection for specimens used in molecular analyses. - NC State University Teaching Collection - approximately 60 drawers of insects used in our insect systematics course (ENT 502). - NC State University Outreach Collection - approximately 8 drawers used for outreach. Holdings of North Carolina insects and of Hemiptera are especially outstanding. The worldwide collection of non-heteropteran Hemiptera, along with NCSU&#39;s extensive literature collections on these lineages, form an unduplicated resource for research on these insects. The NCSU Insect Collection has several other outstanding research collections (mainly Lepidoptera, Acari, Anthophila (the bees), Diptera, Coleoptera, Heteroptera, Orthoptera, and Collembola) within it and associated assemblages of literature that are of international importance.

Priority: high

License: Unspecified

Bibliographic reference: https://news.ncsu.edu/2017/09/insect-museum-grows-2017/

Comments: Found via Twitter news item. Retweeted with map showing global occurrences for Auchenorrhyncha, which remain all but absent in the Caribbean: https://www.gbif.org/occurrence/map?q=Auchenorrhyncha&amp;has_coordinate=true&amp;has_geospatial_issue=false

Dataholders contact information: [Bob Blinn](bob_blinn@ncsu.edu), Collection Manager

Users contact info: @kcopas

**Comment by ahahn-gbif** [comment]
Publisher registered September 2020, no datasets published so far. Likely supported through the SCAN network, but need to check up.

**Comment by CecSve** [comment]
Seems to be in GBIF now? https://www.gbif.org/dataset/e6b15dc0-d70e-446b-bf28-4ddb1a9f4f41 Bob is a contact on the dataset and it is hosted by iDigBio.
