### ISSUE TITLE
Project Roadkill

### ISSUE THREAD

**Issue by kcopas** [gbif/data-mobilization#87]
Dataset link: http://roadkill.at/en

Region: global

Taxon: all life

Type: occurrence

Why is this important: The goal of this citizen science is to get an overview of numbers and patterns of road-killed vertebrates, in hope of helping local authorities direct mitigation actions toward roadkill hotspots. The project combines the expertise and the commitment of citizens with open data to address biodiversity loss and road safety.

Priority: medium

License: Unspecified

Comments: international project based in Vienna

Dataholders contact information: [Florian Heigl](florian.heigl@boku.ac.at), Institut für Zoologie, Department für Integrative Biologie und Biodiversitätsforschung, Universität für Bodenkultur Wien

Users contact info: @kcopas

**Comment by ahahn-gbif** [comment]
The project is registered as a publisher (https://www.gbif.org/publisher/cec55b6c-5728-473a-b1b5-f045b3f494f6). They started working with BioCASe to get the data published, but we have not recent status update on this. The start of the collaboration pre-dated the establishment of the European regional IPT, and may need follow-up.

**Comment by ahahn-gbif** [comment]
Last status from October 2019: in preparation of a data paper to be published alongside the data. Follow-up from GBIF Dec 2020 so far without response or further news

**Comment by ahahn-gbif** [comment]
https://www.gbif.org/dataset/d0d5ef85-71b2-4da6-b6f6-c1c3d60987d3
closing
