### ISSUE TITLE
UK Ladybird Survey

### ISSUE THREAD

**Issue by gbif-portal** [gbif/data-mobilization#9]
## UK Ladybird Survey

Dataset link: http://www.ladybird-survey.org/

Region: UK

Taxon: Coccinellidae

Type: occurrence

Why is this important: This is a big citizen science initiative in the UK and particularly important for engaging public in tracking invasives (e.g. the Asian Harlequin ladybird).

It was in GBIF before through the NBN: http://www.gbif.org/dataset/d5314de0-8871-4edd-9853-55d77eb09c79/activity?&amp;offset=870 

I presume it was lost due to licensing.  This will be an important dataset for the species trend tool (e.g. to show invasions)

Please can we contact the relevant people here and try and encourage it&#39;s publication again?
http://www.ladybird-survey.org/contact.aspx

Priority: high

License: Unspecified

Dataholders contact information: http://www.ladybird-survey.org/contact.aspx

Users contact info: trobertson@gbif.org

**Comment by kcopas** [comment]
Best to work this through Ella Vogel <e.vogel@nbn.org.uk> at NBN, who handled the day-to-day on their re-licensing. She could probably tell you give you the basic status of this dataset without even checking.

**Comment by CecSve** [comment]
There are two datasets from the UK Ladybird Survey: https://www.gbif.org/dataset/68fa8801-0b3e-400e-afa6-5ad08e0f1e4c and https://www.gbif.org/dataset/b4c0c858-f6f3-415f-aec1-f7e3534a8126 which might not be on purpose. Will contact NBN.
